stages:
  - test
  - plan
  - apply
  - provisioning
  - destroy

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

.terraform-image: &terraform-image
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

.terraform-before_script: &terraform-before_script
  before_script:
    - export TF_VAR_do_token=${DO_TOKEN}
    - export TF_VAR_cloudflare_zone=${CLOUDFLARE_ZONE}
    - export TF_VAR_cloudflare_token=${CLOUDFLARE_TOKEN}
    - export TF_VAR_persistent_home_volume_from_snapshot=${PERSISTENT_HOME_VOLUME_FROM_SNAPSHOT}
    - rm -rf .terraform
    - terraform --version
    - terraform init

terraform validate:
  stage: test
  <<: *terraform-image
  <<: *terraform-before_script
  script:
    - terraform validate

terraform plan:
  stage: plan
  <<: *terraform-image
  <<: *terraform-before_script
  script:
    - terraform plan -input=false -out "planfile"
  dependencies:
    - "terraform validate"
  artifacts:
    paths:
      - planfile
  cache:
    paths: 
      - ./terraform.tfstate
      - ./terraform

terraform apply:
  <<: *terraform-image
  <<: *terraform-before_script
  stage: apply
  allow_failure: false
  script: 
    - terraform apply -input=false "planfile"
  dependencies:
    - "terraform plan"
  needs:
    - "terraform plan"

.provisioning:
  stage: provisioning

terraform destroy:
  <<: *terraform-image
  <<: *terraform-before_script
  stage: destroy
  script:
    - terraform destroy -input=false
  needs:
    - "terraform apply"
