stages:
  - test
  - plan
  - apply
  - provisioning
  - destroy

variables:
  TF_VAR_do_token: $DO_TOKEN
  TF_VAR_cloudflare_zone: $CLOUDFLARE_ZONE
  TF_VAR_cloudflare_token: $CLOUDFLARE_TOKEN

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

.terraform-image: &terraform-image
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

.terraform-before_script: &terraform-before_script
  before_script:
    - export TF_VARS_do_token=${DO_TOKEN}
    - export TF_VARS_cloudflare_zone=${CLOUDFLARE_ZONE}
    - export TF_VARS_cloudflare_token=${CLOUDFLARE_TOKEN}
    - rm -rf .terraform
    - terraform --version
    - terraform init

validate:
  stage: test
  <<: *terraform-image
  <<: *terraform-before_script
  script:
    - terraform validate

plan:
  stage: plan
  <<: *terraform-image
  <<: *terraform-before_script
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

.terraform apply:
  stage: apply
  allow_failure: false
  script: 
    - terraform apply

.provisioning:
  stage: provisioning

.terraform destroy:
  stage: destroy
  script:
    - terraform destroy 
