stages:
  - test
  - plan
  - apply
  - provisioning
  - destroy

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

.terraform-image: &terraform-image
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

.terraform-before_script: &terraform-before_script
  before_script:
    - export TF_VAR_do_token=${DO_TOKEN}
    - export TF_VAR_cloudflare_zone=${CLOUDFLARE_ZONE}
    - export TF_VAR_cloudflare_token=${CLOUDFLARE_TOKEN}
    - export TF_VAR_persistent_home_volume_from_snapshot=${PERSISTENT_HOME_VOLUME_FROM_SNAPSHOT}
    - export TF_VAR_persistent_home_volume_snapshot_name=${PERSISTENT_HOME_VOLUME_SNAPSHOT_NAME}
    - rm -rf .terraform
    - terraform --version
    - apk add -U --no-cache jq
    - jq --version
    - terraform init

terraform validate:
  stage: test
  <<: *terraform-image
  <<: *terraform-before_script
  script:
    - terraform validate

terraform plan:
  stage: plan
  <<: *terraform-image
  <<: *terraform-before_script
  script:
    - terraform plan -input=false -out "planfile"
  dependencies:
    - "terraform validate"
  artifacts:
    paths:
      - planfile

terraform apply:
  <<: *terraform-image
  <<: *terraform-before_script
  stage: apply
  allow_failure: false
  script: 
    - terraform apply "planfile"
    # info over hoe dit te doen --> https://stackoverflow.com/questions/65315202/can-i-set-terraform-output-to-env-variables
    # deze echo verplaatsen naar de terraform apply job en van daar de inventory schrijven en doorgeven als cache/artifact.
    - terraform output -json | jq "droplet.public_ip" # er bestaat ook een flag om met JQ direct een shell command uit te voeren waar JSON.var in het cmd gebruikt kan worden
    # - echo "$cloudtop-public-ip ansible_ssh_private_key_file=../files/ci-cloudtop-ci-cldtp_ssh ansible_user=root" > inventory
  dependencies:
    - "terraform plan"
  needs:
    - "terraform plan"
  cache:
    paths: 
      - ./terraform.tfstate
      - ./.terraform
      - ./files

.provisioning:
  stage: provisioning
  script:
    - cd ansible
    - ansible-playbook -i inventory playbook.yml

terraform destroy:
  <<: *terraform-image
  <<: *terraform-before_script
  stage: destroy
  script:
    - terraform destroy --auto-approve
  needs:
    - "terraform apply"
  when: manual
  cache:
    paths: 
      - ./terraform.tfstate
      - ./terraform